Feat: Bag
UMC-TRIPY/back-end-spring pull request #11
Opened 2023-12-27 18:12 UTC by yerim216

## 요약

- 설계 되어있는 ERD 기반으로 entity 매핑을 진행하였습니다. 
- 도메인 디렉터리를 생성하였습니다. 

## 상세 내용
bag
bagMaterials
city
cityPlan
continent
conversation
country
countryMaterial
currency
friend
landmark
materials
planFriends
post
postFile
postTag
tag
timePlan
travelPlan
user
디렉토리 생성 및 엔티티 매핑

## 테스트 확인 내용

## 질문 및 이외 사항

- PlanFriend 테이블 매핑하는 부분에서 여러분들의 의견을 묻고싶은 부분이 생겼습니다. 
본래는 travelPlan(여행계획) 테이블과 Friend(친구) 테이블을 매핑하였는데(즉, 여행 게획과 친구 관계 인덱스를 매핑),
여행 계획에는 계획을 만든 user id가 존재하고, 이를 친구 관계 id와 매핑하는 부분이 이상하다고 생각해서 plan과 user 테이블을 매핑하도록 변경하였습니다. 
1. travelPlan 초대는 친구만 가능해서, 이 부분을 예외처리 하는 코드를 작성하는 방법
2. 복합키를 사용해서 PlanFriendId라는 별도의 복합키 클래스를 만들고, 이를 PlanFriend 엔티티의 @IdClass로 지정하는 방법
두 방법 중에 고민이 돼서, 여러분들의 의견을 듣고 싶습니다. 

우선 1번 방법으로 설계해서 올려놨습니다!

## 이슈 번호

- #9

2023-12-28 03:18 UTC, tjdgns8439 approved these changes
LGTM

2023-12-28 05:25 UTC, gourderased commented
예외처리 방식이 간단해보이긴합니다. 2번의 경우 회의때 자세히 설명해주시면 좋을 것 같습니다!

2023-12-28 05:38 UTC, gourderased requested changes
훈 말대로 대륙 - 나라 - 도시 관계만 일대일과 다대일을 확인하여 수정해주시면 좋을 것 같습니다! 수정 후 request다시 날려주세요!

2023-12-28 06:49 UTC, minhyeokDev requested changes
다른 분들이 말씀하신 부분이랑 제가 말씀드린 수정 부탁드리겠습니다!
너무 잘하셨습니다 !! Controller랑 Service,Repository까지 생성하시느라 고생많으셨습니다 ㅠㅠ

2023-12-28 06:49 UTC, minhyeokDev commented on src/main/java/com/example/tripy/domain/traveltimeplan/TravelTimePlan.java
> +    private String plan_url;
line_color, image_url, plan_url을 카멜케이스로 수정 부탁드려도 될까요?

2023-12-28 06:50 UTC, minhyeokDev commented on src/main/java/com/example/tripy/domain/cityplan/CityPlan.java
> +    private City city ;
여기 ; 붙여주시면 감사하겠습니다 ㅎㅎ

2023-12-28 06:52 UTC, minhyeokDev commented on src/main/java/com/example/tripy/domain/currency/Currency.java
> +    private String currency_en;
여기도 혹시 스네이크 케이스 쓰신 이유가 따로 있을까요?!

2023-12-28 17:00 UTC, yerim216 commented on src/main/java/com/example/tripy/domain/currency/Currency.java
> +    private String currency_en;
erd 보고 적으면서 실수가 있었던 것 같습니다 😂

2023-12-29 07:11 UTC, minhyeokDev commented on src/main/java/com/example/tripy/domain/traveltimeplan/TravelTimePlan.java
> +    private String line_color;
여기 하나만 수정 부탁드립니다!

2023-12-30 02:59 UTC, gourderased approved these changes
고생하셨습니다~~!

2023-12-30 04:12 UTC, minhyeokDev approved these changes
수고하셨습니다 !!

2023-12-30 05:26 UTC, merged